### ISSUE TITLE
Changing database in same connection opens tables list of all previously used DBs

### ISSUE THREAD

**Issue by BornaP** [sqlectron/sqlectron-gui#103]
When changing between databases in the same connection, previously used databases remain collapsed although one clicks minimize button to keep tables list hidden. 

To reproduce bug:
1. Open connection
2. Click 'minus' button to minimize tables list of currently used database
3. Double click another database
4. Both database lists are now open

**Comment by maxcnunes** [comment]
I spent some time trying to fix it. But it is a bit more complicated then I thought.
Nowadays every time a new DB connection is opened. We [refresh the app](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/containers/query-browser.jsx#L133).
Because of that I see 3 solutions:

1. Do not use `history.pushState` anymore to connect into a new DB. (I guess would be some quite work).
1. Use nested routes. This way we could associate each database item in the side bar with its own route. I think when you change a inner route the redux will keep the same state to the parent components. But I not sure about it. (I guess would be some quite work too).
1. *I think this the worst approach. But it is the easiest as well.* Store any state that must be kept between connections.

**Comment by maxcnunes** [comment]
@krolow any ideas?

**Comment by BornaP** [comment]
Regarding the last approach, you were thinking that we should store state object between connections on same server(client) regarding info about toggled menus and than on each database select (app refresh), render database list accordingly?

**Comment by maxcnunes** [comment]
In the last approach I was thinking in keep the state of toggled databases in the database store (reducer state). This way the state wouldn't be lost on changing the database connection (which changes the page). But I don't think this is a good approach. At least all examples I have seen in internet for filter states, it is stored inside the component instead of the store.

But I found something weird right now. If there is something in the database filter input on changing the database. That value is not lost as the toggled databases. Maybe we could do the same for the toggled databases. The difference in the filter databases is that the state is stored in the container ([here](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/containers/query-browser.jsx#L151)) instead the element.

**Comment by maxcnunes** [comment]
But I still prefer the first option.

**Comment by maxcnunes** [comment]
I have started implementing the first option. @BornaP I suggest waiting for these changes before working in anything else. Otherwise, probably you gonna have a lot stuff to resolve conflict during the merge.

**Comment by BornaP** [comment]
@maxcnunes  Okay cool, thanks for the heads up :)

**Comment by maxcnunes** [comment]
@BornaP I have not fixed it yet. But my last commit https://github.com/sqlectron/sqlectron-gui/commit/811098cc18a2a6698ec0ad93bcd19e0dca90507d allow you keep going in the other stuff you are working on.

**Comment by maxcnunes** [comment]
Fixed on commit 9967d66ef7c268d6e0bf8da4dccbbeb2ce5e8df4
