### ISSUE TITLE
Installer: Windows installer not displaying properly

### ISSUE THREAD

**Issue by darkwisperer** [sqlectron/sqlectron-gui#127]
OS: Win7
App Versions: 1.6, 1.6.2, 1.7
using: SqlectronSetup-1.7.0.exe

This is a minor bug where the installer is not rendering properly. 
See below:
![image](https://cloud.githubusercontent.com/assets/740476/14829975/26c5bafe-0ba3-11e6-8b64-bfd5d02f14a5.png)

**Comment by darkwisperer** [comment]
Can some one else verify?

**Comment by maxcnunes** [comment]
Do you mean that image? That is a default gif visible during the installation. https://github.com/electron-userland/electron-builder/wiki/Options#buildwin

If the problem you are describing is really that I can ask to my brother (how created the Sqlectron logo) to  create a gif for Sqlectron installation.

**Comment by darkwisperer** [comment]
Oh. Yes it is the [spinner gif](https://github.com/electron/windows-installer/blob/master/resources/install-spinner.gif). That gif is a little confusing as to its purpose in the install.

**Comment by maxcnunes** [comment]
@markcnunes [this gif](https://github.com/electron/windows-installer/blob/master/resources/install-spinner.gif) is visible during the installation of the app on Windows.

But since that is too much generic is a bit confusing what that represents.

Could you prepare a gif for Sqlectron with a spinner and some describing message such as "Installing... Please wait."?

**Comment by maxcnunes** [comment]
Implemented in this commit https://github.com/sqlectron/sqlectron-gui/commit/ee4c7b8a2cbb1d5991a44e20899cba6be7bea0fa
