### ISSUE TITLE
Opening Databases is not intuitive

### ISSUE THREAD

**Issue by cperezabo** [sqlectron/sqlectron-gui#133]
First of all (and after you discover how) it feels like if it would have a delay when you click on the database at the sidebar
But the most important thing is that the "+" for expanding the database tables isn't there by default!. You first have to discover that you have to double click the database name to open it, but just the name, because I was clicking the database box and nothing happened until I tried on the name. Then, the "+" appeared and the tables showed up.
The cursor pointer never changed to say me "hey, you can click or double click here"

**Comment by maxcnunes** [comment]
At the beginning we had a pointer cursor on passing the mouse over the database. But we changed that to default cursor because you have to double click to open the database. And the pointer cursor is a common style for one click. The database name has a tooltip saying you can click twice to open the database. But that only appears if you stop the mouse over the database name.
But you are right, we have to make it more clearer for new users. I going to try out some stuff and see which goes better.
Thanks for the feedback.

**Comment by cperezabo** [comment]
I think the first approach was better!. It is simpler to click once instead of twice.
And further more if you have to see a tooltip to know you can double click the database name!

**Comment by BornaP** [comment]
I'm not sure if it is a good practice to require only a single click for opening new database connection, because user can click it by mistake and open new connection redundantly.

**Comment by krolow** [comment]
I agree :+1: to have one click back and cursor pointer

**Comment by cperezabo** [comment]
@BornaP At least is more intuitive!. UX is awful as is today. I double click a database and no "Opening..." message is displayed, further more I have to discover where to double click! in the name? in the surrounding area? in the db icon at the right? Opening a new connection on a "mistaken click" is paradise compared with the time it takes to discover where you have to click!

**Comment by krolow** [comment]
yeah for sure @cperezabo, that's why we are welcome to PR and changes, it would be good to receive from you a PR to improve such behavior... just to get a context, we (when i say we, mainly @maxcnunes) we have built that because we haven't found a good App to query across platform in PgSQL, it was the begin of the idea of sqlectron...

so for sure it have a lot to improve as we are **developers** building something to use in our daily bases, it has a lot of UX and features to improve...

based on that is why we encourage others to use it, as well improve it by creating PR...

in the meanwhile it seems enough to only change it back to mouse "pointer cursor" and add one mouse click, what do you think?

**Comment by maxcnunes** [comment]
I disagree with these options:
 * pointer cursor + one click: as @BornaP said it will make users open a new connection by mistake.
 * pointer cursor + double click: is not the expected behavior for the pointer cursor. Pointer cursor must trigger an action in the first click.

I propose to have the same behavior of MySQL Workbench.
* All the databases have a collapse icon.
* It always use default cursor hover the database.
* Clicking twice in the whole row of the database (not only the name) will open a new connection and change the collapse icon to open.
* Clicking twice again collapse the database information and change the collapse button to closed.
* Does not have any tooltip about this behavior.

**Comment by krolow** [comment]
@maxcnunes yeah, collapse sounds a good idea... it would give the felling that you need to click to open that, so for sure it might be as well one approach to go ahead!

**Comment by maxcnunes** [comment]
@cperezabo if you are not interested in diving into the code to implement it just let me know. I don't mind implementing it for next release. Although since it is a simple change this would be a good opportunity to know the code.

**Comment by cperezabo** [comment]
I forked the repository to do that, but I cannot compromise about times since I am complicated with my jobs and university !! 😱

**Comment by krolow** [comment]
@cperezabo excited dude, looking for to see your contributions, as said before we are trying to make this project as welcome as possible to accept PR

**Comment by BornaP** [comment]
I agree with solution Max proposed :+1:

**Comment by maxcnunes** [comment]
I just realized it still working only on clicking in the name. I will try improve that again 😄
