### ISSUE TITLE
Add Support for schema

### ISSUE THREAD

**Issue by eMerzh** [sqlectron/sqlectron-gui#153]
With postgresql and other big databases (oracle, ...) you have schema...
it seems that sqlectron does not support them .... it would be really nice to be able to browse accross distinct schemas :)

**Comment by BornaP** [comment]
Yeah you're right, sqlectron does not support them, it currently reads only public schema of certain database (if DB engine supports schemas). Since only PostgreSQL of all database that we support has schemas, I guess it would require writing some code specific only for postgres case, since the app is hybrid.

**Comment by eMerzh** [comment]
ok... i understant that it's a bit harder than just "display_the_schema=yes"
but would'nt it be possible to at least let the user select a schema at connection time or something ?
or any other workaround ?

because Postgresql support without schema is not really as useful as it could be.

**Comment by BornaP** [comment]
I agree with you on that. We'll see whether to implement schemas in database list so that user can browse between schemas (if they exists) or as you said, enable user to select schema when connecting to database.

I guess first option might be doable with making component that would be hidden when not using postgres (hence when method in back-end, let's call it _getDatabaseSchemas_ , would not return anything).

**Comment by maxcnunes** [comment]
I guess this issue could be break down in 2 PR:

1. allowing the user select the default schema during the connection (in the server management screen).
2. listing the schemas in the database list as @BornaP said.

**Comment by kstr** [comment]
I noticed that tables from another schema are simply not listed on the left side of the screen, but it is possible to include them in a query.  I miss this feature since we use a custom scema in all our databases.

**Comment by abourget** [comment]
Splitting views per schema is a little tricky though, we have cross-schema queries and it'd be annoying not to have completion between schemas too... why not simply list the tables in the `Tables` view, prefixed with their `schema` ?

The search in there could help us navigate.. it does a great job at it.

**Comment by maxcnunes** [comment]
Done on https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.19.0
