### ISSUE TITLE
Feature: Ability to view stored proc definitions for SQL Server

### ISSUE THREAD

**Issue by JediMindtrick** [sqlectron/sqlectron-gui#185]
First, nice work.

On v 1.8.0 there doesn't seem to be any way to view stored procedure definitions for SQL Server.  I am not sure about other databases or versions.

I think I'd be willing to work on adding this feature and submitting PR if the project team is interested. 

Or, if I just somehow missed it, please let me know.

**Comment by maxcnunes** [comment]
Hi @JediMindtrick,

Thanks for the proposed pull request. Although it has already been implemented by @BornaP. If you want to check it out before we release the next version you can run the app from the source.

**Comment by JediMindtrick** [comment]
Great, and thanks for letting me know!   I think I will check it out since
I've actually been using this software at work and the feature is much
needed.

**Comment by BornaP** [comment]
@JediMindtrick First off, it's great to hear you use it often at work :) Secondly, this feature has been implemented with f02161f76eb0d696ea5219ab6e7a0cd1960b382c and 9073f2512cc2751049b11889c890b65f21875870. As Max mentioned earlier, you have to pull latest changes from master to have this option available since no new release has been published since implementing that. 

Option is available on right clicking procedure name.

**Comment by BornaP** [comment]
@JediMindtrick This feature is now available in new release v1.9.0 :)

**Comment by JediMindtrick** [comment]
Got it, looks good.  Thanks.
