### ISSUE TITLE
problems typing in query window when connected to SSH Tunnelled database

### ISSUE THREAD

**Issue by agodlydeciple** [sqlectron/sqlectron-gui#186]
|  Version  | Database Client
|---|---|
|  1.8.0  | MySQL 

---

When typing in the query box when connected to a server through an SSH tunnel, the text disappears or get's overwritten, when typing normally. Only way to avoid the text overwriting / disappearing is to type each individual character. 

![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/683837/15801415/60dea762-2a59-11e6-8d1b-cdd69eedf9d9.gif)

**Comment by maxcnunes** [comment]
Hi @agodlydeciple,

That is weird. Most of the connections I use are over SSH tunnel and that does not happen to me.

**Comment by agodlydeciple** [comment]
yup it only is like that with the SSH tunneled Server. It doesn't do that with my local mysql dev server I use on my laptop.

Another weird thing is when you double click a database when Tunneled  it doesn't open it.  The only way to see the tables in a database is to type a `show tables;` in the query window.

**Comment by maxcnunes** [comment]
On typing in the query box the behaviour should be the same independently whether is a local connection or a remote connection through a SSH tunnel. Since it does not happen to me is hard for me trying to fix it. I guess you could avoid this problem by disabling the auto complete, just include `"enabledAutoComplete": "false"` on `~/.sqlectron.json`.

About to second problem, that does not happen to me either. Although I have include a context menu to refresh the database data. I guess that could sort of solve the problem for you. Is going to be available in the next release.

Sorry. I could not help much.

**Comment by agodlydeciple** [comment]
No worries, chances are there is something weird with my particular setup.

where would I add `"enabledAutoComplete": "false"` in the `~/.sqlectron.json` file? I have tried before the servers tag and within the specific server definition and each time sqlectron doesn't load correctly.

**Comment by maxcnunes** [comment]
This way:
![screen shot 2016-06-04 at 4 55 46 pm](https://cloud.githubusercontent.com/assets/680356/15801752/3fc32d20-2a75-11e6-8705-5957423de6d0.png)
But seems it is not working anymore 😢 . I'm investigating that.
