### ISSUE TITLE
Windows domain required for login to Sql Server

### ISSUE THREAD

**Issue by airdrik** [sqlectron/sqlectron-gui#213]
In our, and probably many other environments employing SQL Server, logging in to the server may require providing the Windows domain along with the username and password.
Often this can be provided by specifying it in the username like: "MYDOMAIN\myuser".  However, when I tried this (and other variants using one or two back or forward slashes) it still rejected my login attempt.

Please add an optional field to supply the Windows domain when connecting to SQL Server databases.

**Comment by maxcnunes** [comment]
Could you provide the error message?

**Comment by airdrik** [comment]
Just a generic login failed. 
If there's some way to get a more specific message, I can look into that on Monday

**Comment by maxcnunes** [comment]
Ok, only that is enough. The app does not have any log file.
The library we use [node-mmsql](https://github.com/patriksimek/node-mssql) has a `domain` property in the connection for what you need. But we have no included that.
Since I don't use mmsql this feature is low priority for me. Not sure when I will be able to implement it. If you are interested in implementing it I could show to you the places you have to change and I would gladly accept a PR for that.

**Comment by airdrik** [comment]
I could probably do that.

**Comment by jaykilleen** [comment]
@maxcnunes as a workaround, would modifying the `.sqlectron.json` work to specify the domain? Another issue I am trying to figure out is specifying whether it is windows authentication or username and password. Hoping the modification of `.sqlectrion.json` would also address this. I'll take a look at the node-mmsql for guidance on this.

Thanks also, this project looks very interesting and I appreciate the work you have done so far.

**Comment by maxcnunes** [comment]
@jaykilleen thanks. I appreciate the feedback :)

Even changing the `.sqlectron.json` manually it would no work because sqlectron-core would not include this property in the connection configuration.
About your issue, this is what node-mmsql describes about the domain:

> domain - Once you set domain, driver will connect to SQL Server using domain login.

If it helps you, here is an example how probably the connection string would look like with the domain.
https://github.com/patriksimek/node-mssql/blob/12255523f892d72d440f06d1ee86a2b214961db1/test/unit/unit.coffee#L39

This week I am working a bit in some features. So I don't mind including this `domain` property in the connection options. But I don't have any domain to test it. It would be a shot in the dark.

**Comment by airdrik** [comment]
I'd certainly be willing to help test out the changes.  Let me know when you have something, of if you have some pointers for where to make the changes myself.

**Comment by airdrik** [comment]
I just downloaded and tested sqlectron 1.17 which advertises the ability to specify the windows domain, and it works!

Thank you.
