### ISSUE TITLE
Feature request: adding support to sqlite

### ISSUE THREAD

**Issue by aborruso** [sqlectron/sqlectron-gui#215]
Thank you

**Comment by maxcnunes** [comment]
This would be really good. Actually it has been requested already https://github.com/sqlectron/sqlectron-core/issues/26. @AngeloR was working on that. But I am not sure he had any progress on that.
If you are interested on implementing it I would gladly accept a PR. Otherwise I probably will implement it in the future. I just don't know when :smile:

**Comment by aborruso** [comment]
@maxcnunes thank you for your reply. I'm not able to implement it :(

**Comment by maxcnunes** [comment]
Done on https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.19.0
