### ISSUE TITLE
Allow queries to be cancelled while it is executing

### ISSUE THREAD

**Issue by elhh82** [sqlectron/sqlectron-gui#221]
This is different from https://github.com/sqlectron/sqlectron-gui/issues/87

currently once a query is issued and the db is processing there is no way to cancel a query. Sometimes you want to do this because your realized you did something bad.

I think the client is pretty much unusable without this.

**Comment by maxcnunes** [comment]
Ouch "pretty much unusable" :cry: Even without that feature I think this app still quite useful. At least I have never needed to do that using this app or even with any other client. But I get your point, that would be a great feature.
I have seen some people doing that manually, listing the queries running in the database and killing them. I guess that is something you can do in any database. Could you let me know which client you use has this feature?
Since that is something I have never needed to use. I wont try to implement it right now. But if you are interested in sending a PR I would gladly accept that.

**Comment by eMerzh** [comment]
mmh i think pgadmin does this, and sequelpro too.

**Comment by elhh82** [comment]
I think any decent SQL Client does this, I would think this is one of those super basic functionalities. So far we've been using navicat lite, it allows cancels, we also tried wagon and thas also allowed cancels. In fact my favourite client psql allows cancels via ctrl-c :)

Every one makes big mistakes and especially if you're working with big datasets, those mistakes can be painful and being able to cancel allows you to move on.

Imagine if i started a query like select * from 100_M_row_fact_table a join 10000_row_dimension_table b on a.b_id = b.id

Oh fuck i forgot to issue a limit.

I would look for the cancel button yes?

**Comment by maxcnunes** [comment]
Fair enough. I have investigated the implementation for this feature and seems only mysql is gonna a bit more complicated.

* **postgres** client has support already to cancel the query. [reference](https://github.com/brianc/node-postgres/blob/b1b2801c710d550f2b10910dfd49ad51bbf569fd/lib/index.js#L81)
* **mysql** does not have support, would require finding the current process id and killing it [reference](https://github.com/mysqljs/mysql/issues/137)
* **mssql** client has support already to cancel the query. [reference](https://github.com/patriksimek/node-mssql#cancel)
* **cassandra** does not have support, and I think is not even possible to do that trick to kill the process (I am ok skipping this feature for this client)

Since it is a important feature I don't mind implement it. But right now I'm not much available to implement that. @elhh82 if you are interested on implementing that, please do.
