### ISSUE TITLE
Like Wagon, utilize lists instead of tabs

### ISSUE THREAD

**Issue by krainboltgreene** [sqlectron/sqlectron-gui#252]
Tabs hide information and there's no way you could ever possibly make tab name reflect the tab content well enough to make tab searching easy. After 6 queries I'm basically hunt-and-pecking my way through tabs.

Wagon, a GUI that has closed down, utilized lists instead of tabs. Here's what we could do for SQLectron:

<img width="1445" alt="screen shot 2016-10-09 at 7 57 11 pm" src="https://cloud.githubusercontent.com/assets/334809/19226058/f543cfbc-8e5a-11e6-8641-dff73656a61f.png">

**Comment by krainboltgreene** [comment]
(By the way, I would love to work on this if approved)

**Comment by BornaP** [comment]
Sure, go ahead, all PR are very welcome! :)

I too agree on tabs naming convention you proposed.

**Comment by krainboltgreene** [comment]
That's great to hear! I'll work on it soon, the data team I work with is super bummed Wagon is gone and they'll love that they can get something better.

**Comment by BornaP** [comment]
That's even nicer to hear ;)

**Comment by eMerzh** [comment]
i'm not sure about what was the wagon way...

for me, we clearly have to rework the tabs because, they don't really work,  and doesn't let you multiple connections without creating another window.
But not sure how the list tab work, if i understand correctly is each tab is below one another,  so all always displayed ?

that could also rapidly become a mess no ?

**Comment by maxcnunes** [comment]
@krainboltgreene it is really nice to hear you are interested in contributing to the project. The idea of replacing the tabs with list seems a good approach. At least with small queries and table results it looks could work really well. Although with the opposite I'm not sure about that. Seems would be even worse because you could not see all the open "tabs" without scrolling the whole page.
So before writing a PR for this I guess we could discuss more about it. Sure we can find a good approach for this problem. At least once we add support to rename tabs the use will be able to set the best name for each one of them. So this could already improve a lot the problem with the tab names.
