### ISSUE TITLE
The sidebar isn't very useful with production Heroku access

### ISSUE THREAD

**Issue by krainboltgreene** [sqlectron/sqlectron-gui#262]
I can't quite show you what I mean, but currently when I connect directly to one database that happens to be on heroku the sidebar shows a list of the 140 databases, all with sluglike names (i.e. `d14b9ss239j9f`). It slows down the entire application.

What's the vision/concept behind this UI and is it really need to be a default-on component?

**Comment by krainboltgreene** [comment]
Since I only have credentials for one database I can't even access any of the other stores and there's no indication which store is mine. I'll see about rushing #251

**Comment by maxcnunes** [comment]
Well the concept behind the sidebar is list all available dbs for the connected server. With the current app what you could do is filter by the db name. This should improve the performance and let you focus your current working database. At least I'm used to do that.

**Comment by krainboltgreene** [comment]
It still slows down the application for some reason, and filtering is annoying considering the database name.

Is there a particular value to showing *all* databases when you connect to a specific database?

**Comment by maxcnunes** [comment]
Sorry, I thought that would improve the performance. Actually there is a PR to improve the performance in the sidebar for large list of databases https://github.com/sqlectron/sqlectron-gui/pull/200. But that PR had some UI problems and has never been merged.

In my case I work a lot with micro services. So in my daily job I usually have to access many DBs from the same server at same time. A list with all DBs available helps a lot. Because once I'm connected to the server I have easy access to all other DBs. But if that does not work for you. Maybe we could include a checkbox somewhere to allow show only the DB specified in the server connection.

**Comment by krainboltgreene** [comment]
That makes a lot of sense. I wonder if there's a middle ground here that doesn't involve a checkbox. I'll play around with some ideas. I appreciate the insight!

**Comment by maxcnunes** [comment]
@krainboltgreene  I have added support to configure a preload filter for database and schema in https://github.com/sqlectron/sqlectron-gui/releases/tag/v1.19.0. You have to configure it manually for while in the `.sqlectron.json`. With that configuration you will be able to load only the database/schema which are useful for you and by that improve the usability on large servers like Heroku.

**Comment by krainboltgreene** [comment]
So. Much. Better.
