### ISSUE TITLE
Can't connect localhost MySql (mariadb) on localhost

### ISSUE THREAD

**Issue by blackPantherOS** [sqlectron/sqlectron-gui#264]
mysql -p command and phpmyadmin working fine on 'localhost' as host

but I can't connect to same server with sqlelectron-gui  or sqlectron-core with 'localhost' (not 127.0.0.1)

Error message: Error: connect ECONNREFUSED 127.0.0.1:3306  

(ignored 'localhost' as hostname)

**Comment by maxcnunes** [comment]
Really? That should work just as fine as the other clients. Probably the error message shows IP instead of the domain because once the DNS server resolve the domain name it uses the IP to connect. Are the mysql and phpmyadmin clients running in the same machine of the sqlectron? Are you sure your mysql server is running in your host machine?

**Comment by blackPantherOS** [comment]
Yes, the phpmyadmin running on localhost and working.. The commandline as well:

> vector@core4〉~〉mysql -u**** -p******* -hlocalhost
> Welcome to the MariaDB monitor.  Commands end with ; or \g.
> Your MariaDB connection id is 14
> Server version: 10.1.18-MariaDB blackPanther MariaDB Server
> 
> Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

But access not enabled on 127.0.0.1:

> vector@core4〉~〉mysql -u**** -p**** -h127.0.0.1
> ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused")

Your applcation not accept the **'localhost'** as hostname, triggered to 127.0.0.1

**Comment by maxcnunes** [comment]
We pass ahead the hostname exactly as it was typed in the form to the mysql driver https://github.com/mysqljs/mysql. So it should accept any hostname. 

Maybe is not possible to connect to a Maria DB through the Mysql support. Then would require using the proper maria db driver for that https://github.com/mscdex/node-mariasql. 
I will try test it later.

But I am curious how you are able to connect with the hostname *localhost* and is not able to connect with the hostname *127.0.0.1*. Since the localhost name will be resolved to 127.0.0.1 by the DNS server. Could you please check if your localhost is really resolving to 127.0.0.1 with:

```
ping localhost
```

**Comment by maxcnunes** [comment]
@blackPantherOS are you using ssh tunnel? I just realized we use a fixed host for ssh tunnel https://github.com/sqlectron/sqlectron-core/blob/master/src/utils.js#L68. It may could be the reason for your problem.
