### ISSUE TITLE
Cannot switch to fifth tab once created

### ISSUE THREAD

**Issue by thoma87** [sqlectron/sqlectron-gui#311]
**Issue**
With many tabs open, I can only switch to the first four. Tabs five and beyond can be closed and have their titles edited, but clicking them does not switch to them.

**To Replicate**
Open a new SQLectron window.
Create five or more tabs.
Switch to tabs 1-4.
Try to switch to tabs 5+.

**Comment by tengis** [comment]
I had a little investigation on this issue. So i found where the exact issue is. 

Since using **TabList** component inside custom <div>'s it created this issue. And reason behind this **react-tabs**'s count helper only counts **TabList** as a first child if it's not a first child just doesn't count.

Please see link below
https://github.com/reactjs/react-tabs/blob/master/src/helpers/count.js#L7

**Comment by maxcnunes** [comment]
Humm that is bad. I will try take a look on that soon. @tengis thanks for the investigation.

**Comment by s-kem** [comment]
For the sake of it being mentioned within the sqlectron repository, the problem is in the `getTabCount` function of the `Tabs` component in the forked version of `react-tabs` that sqlectron relies on.

It's counting how many children the 0th child of the `Tabs` component has -- the way `query-browser` was written the 0th child is not the list of tabs, but a div with 4 children.

Due to that, `getTabCount` was always returning 4, and when we clicked on the 5th tab or beyond, it failed a check in `setSelected` at `if (index < 0 || index >= this.getTabsCount()) return;`

**Comment by maxcnunes** [comment]
Thanks @s-kem for taking care of this issue!!
