### ISSUE TITLE
Missing user management section.

### ISSUE THREAD

**Issue by AceVik** [sqlectron/sqlectron-gui#405]
The only one reason, i don't want to use my current tool is, that it don't has a user/privileges management.

With windows i always use HeidiSQL, but on linux with wine it sucks. (Same on Mac)

I want a crossplatform tool that is like HeidiSQL and my hope is sqlectron become such a powerfull tool.

**Comment by maxcnunes** [comment]
Hi @AceVik, thanks for your feedback. But I'm not sure we will get to a point where we have such feature. And here is why: Sqlectron was initially designed to be a simple SQL tool with cross-platform and database support. I imagine supporting a user management for: mysql, mssql, postgres, and etc. would be quite a work and we don't have developers enough contributing to the code base in order to develop and maintaining that feature. So I rather keep it simple than adding such complexity which could easily lead to bugs without a good support. Sorry 😞
