### ISSUE TITLE
Sqlectron (GUI) binary doesn't start

### ISSUE THREAD

**Issue by wunderlich** [sqlectron/sqlectron-gui#427]
Hello,

I want to use *Sqlectron* at my computer science course at school. We still have to you use Windows 7 with a custom server backend an domain log in.

I downloaded the latest archive [Sqlectron-1.29.0-win.7z](https://github.com/sqlectron/sqlectron-gui/releases/download/v1.29.0/Sqlectron-1.29.0-win.7z). Am I right, that this version can be used without installation (only extract the archive and start `Sqlectron.exe`)?

Unfortunately, this doesn't work. When I double-click at the exe, nothing happens.

Installing *Sqlectron* (` Sqlectron-Setup-1.29.0.exe`) works, but because our Windows profiles are resetted at every restart, my students have to reinstall the program every lesson.

Any ideas? It's a pity, because *Sqlectron* is great for introducing SQL because of its simplicity.

**Comment by MasterOdin** [comment]
On my computer using Windows 10, I am unable to replicate having any issue on running the above. Not sure what the issue could be, but thoughts would be:

1. Was using Windows 7 32-bit, which would not work with the above. We now publish 32-bit binaries and so can use that instead.
2. Some issue where `%APPDATA%` cannot be read / accessed which is causing a hard-crash on sqlectron, maybe?

Addressing this would require additional details on the Windows setup, otherwise not sure much can do on to fix this.
