### ISSUE TITLE
 missing dependency "libgconf-2-4"

### ISSUE THREAD

**Issue by arakash92** [sqlectron/sqlectron-gui#449]
I used the "Sqlectron_1.29.0_amd64.deb" on ubuntu 18.04 LTS and it didn't work, so I tried running it from command line and it complained about a missing dependency so I had to install it manually (libgconf-2-4).

I assume this dependency should be added to the deb file itself?

**Comment by seantcanavan** [comment]
It is indeed missing from the deb file. Confirming here. Found the workaround here via Google: https://github.com/electron/electron/issues/1518

`sudo apt-get install libgconf-2-4`

**Comment by LoveSponge** [comment]
Issue present in 1.30.0 on Arch install with Pacman.
Are there any updates on this? Do we even know what is causing it?

**Comment by seantcanavan** [comment]
@LoveSponge the project is dead - switch to DBeaver: https://www.archlinux.org/packages/community/x86_64/dbeaver/

**Comment by MasterOdin** [comment]
> Are there any updates on this? Do we even know what is causing it?

What's causing it is that Chrome added a dependency on libgconf to function on Linux, except that it does not come with Chrome nor is it installed by default on most distros. After spending yet another day trying to get VirtualBox and Debian / Ubuntu OS to run inside of it (with both failing at different points of installation / runtime), I'm going to kick this issue and fixing it "properly" down the road to a later version and instead just update the README to say you need to install libgconf if on Linux. There's a good chance that just upgrade the version of electron / electron-builder that sqlectron uses will resolve this as well.

**Comment by LoveSponge** [comment]
@seantcanavan I only realised after posting my comment; 
Since then i've found [Beekeeper Studio (link)](https://github.com/beekeeper-studio/beekeeper-studio/), a great alternative with active maintinence.

**Comment by MasterOdin** [comment]
This project does have active maintenance, though my time is split amongst a number of things.

I want to think this issue has been fixed with 1.31.0, but it's hard for me to say as at least at the moment, I do not have a Linux environment to test on natively, and my last few attempts at setting up a VirtualBox image has been met with a number of annoying problems just installing debian / ubuntu, let alone getting them to run. It will definitely be fixed in 1.32.0 as I upgrade the electron and electron-builder dependencies which should definitely force `gconf` to be a dependency by default of building the project.

**Comment by MasterOdin** [comment]
This was fixed in #507.

**Comment by dev-rsonx** [comment]
help I don't want to build from the source. discover says "dependency resolution failed". But it does not tell what dependency  :<

**Comment by seantcanavan** [comment]
@dev-rsonx just switch to dbeaver already it's free and a million times better. It's fully cross-platform as well. https://dbeaver.io/download/

**Comment by MasterOdin** [comment]
@dev-rsonx what linux distribution and version are you using?
