### ISSUE TITLE
Close non selected database

### ISSUE THREAD

**Issue by JostCrow** [sqlectron/sqlectron-gui#66]
Now when I switch database inside the postgres database then the old one still shows all the columns a good idea would be to not show the columns of the non selected database.

**Comment by maxcnunes** [comment]
When you say "columns" you mean "tables" right?
Well, this is an expected behaviour. Since I usually work with micro services is pretty common I have to go over different databases to fetch the final data. If you don't want go get distracted by the other databases maybe you could just filter in the search box by the current selected database. Ok?

**Comment by JostCrow** [comment]
Ok. Thanks. Sorry for the late response.
