### ISSUE TITLE
Connection Error Error invoking remote method 'DB_CONNECT': Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Gyde04** [sqlectron/sqlectron-gui#671]
Tried to test mySQL connections and it gives me this error message

**Comment by janyajoshi** [comment]
same for me while using with amazon aws

**Comment by Aryaman19** [comment]
Hey, I was also having this same issue when I tried to connect with aws rds, but the actual problem was in the inbound rules defined for the database instance. I changed my inbound rules and I got connected to the aws rds through sqlelectron.

P.S: If you cannot connect using sqlelectron, then try connecting using terminal, in my case there also I got an error that leads me to the StackOverflow and eventually to my inbound rules set for the database instance created in aws rds.

**Comment by mohit13100** [comment]
if you have used default VPC do allow traffic from internet or allow all traffic from security group in aws

**Comment by UpadhyeN** [comment]
Hi, if you are using custom VPC. then make sure that in the route table all internet traffic is going to Internet gateway. so edit inbound rules and change the route table.
![image](https://user-images.githubusercontent.com/43287536/219966289-763dac49-b758-4e02-8ace-bfaf44a422de.png)

**Comment by vinothbabu** [comment]
![image](https://user-images.githubusercontent.com/1165332/227868612-bec42a8d-0a0a-4252-bb30-9e074f7e337c.png)

In your RDS -> Select your database and check if its publicity accessible.
