### ISSUE TITLE
Insufficient error details

### ISSUE THREAD

**Issue by saitolabs** [sqlectron/sqlectron-gui#70]
There's a way to add more information about the error?

![error_not_so_descritive](https://cloud.githubusercontent.com/assets/1012457/11788754/c1fba210-a279-11e5-9c17-37e11e0dc4f9.png)

**Comment by maxcnunes** [comment]
I can take a look on this to see if is possible.

By the way I think your problem is in the address. Although is possible use this address format in SQL Server Management Studio, in Sqlectron you need to use IP+Port.
![screen shot 2015-12-14 at 4 09 19 pm](https://cloud.githubusercontent.com/assets/680356/11789359/19f2722a-a27d-11e5-9c2e-f9e21fadef79.png)

To connect through IP+Port I also had to follow these steps:
- http://dba.stackexchange.com/a/62300
- http://dba.stackexchange.com/a/62166

If you are connecting from a different machine you also will need to disable the firewall or create a rule allowing connections to the MSSQL port.

**Comment by saitolabs** [comment]
Thanks, now I'm able to connect :+1:

**Comment by maxcnunes** [comment]
I have improved the error handling during the connection. So, I guess we can close it.
