### ISSUE TITLE
If I try execute a empty or a commented query , I receive a message "Query executed successfully. Affected rows: ."

### ISSUE THREAD

**Issue by camilalabes** [sqlectron/sqlectron-gui#84]
Mesmo sem nenhuma query escrita ao dar ctrl+enter, aparece uma mensagem dizendo que a query foi executada e que linhas foram afetadas.

Se eu tenho duas queries escritas, por ex, dois deletes, porém, um está comentado (para não ser executado), aparecem duas mensagens dizendo que as duas queries foram executadas (deu medo quando isso aconteceu, achei que tinha excluído coisa que não queria).

PS.: nesse caso, de ter dois comandos escritos e um comentado, só diz que executou os dois, caso o comentado tenha um ";" no fim.

**Comment by maxcnunes** [comment]
Fixed the first issue.

I have fixed the second one for PG and MSSQL. But MySQL considers a commented query as a non select query. Since is not possible without hacks to figure it out, this problem will continue to happen for MySQL.

Though to cause less confusion I will include a FAQ window listing the particularities of each client.

Related commit: 719f47096aaa32414dd4572f85396e05a83dce6b
