### ISSUE TITLE
Middle mouse click doesn't close a tab

### ISSUE THREAD

**Issue by brunolm** [sqlectron/sqlectron-gui#89]
When I click on a tab with the middle button it doesn't close.

**Comment by maxcnunes** [comment]
The lib we use to build the tabs (https://github.com/reactjs/react-tabs) does not support the event **onMouseUp**, required to handle "custom" mouse events. So would be required create a pull request to react-tabs including that event before implementing it here. I don't have much interest implementing it because I don't really use it that much. But I would gladly accept a pull request with this feature :smile:

**Comment by BornaP** [comment]
Seems like react-tabs repository is inactive recently (at least admins are), even if someone makes PR it's very unlikely it will be accepted anytime soon.

**Comment by maxcnunes** [comment]
Well, there are a few options for that:

* Implement that on react-tabs and use the new branch (in case they don't accept the pull request).
* Find out another actively maintained react tab component (even better if has that feature already).
* Instead of use the cursor to close the tab. We could implement a shortcut for that (e.g. Ctrl/Cmd+W) ( I would like this one).

**Comment by BornaP** [comment]
I agree with third option that you mentioned. We could implement shortcut for that. Tab can be closed on mouse click anyways (by clicking the x button). Secondly, I see that there are some request for implementing support for custom mouse events on react-tabs, so I think it will be implemented eventually and then we can add that to our app easily.
