### ISSUE TITLE
UI: Add connection requires DB when making a connection

### ISSUE THREAD

**Issue by darkwisperer** [sqlectron/sqlectron-gui#96]
DB client: MSSQL, Mysql
App version: 1.5.0 
OS: Win 7

For both MSSQL and MySQL (not familiar with Postgress), when adding a connection the DB field should be optional since the database is not required to make the connection. I'm not sure if this is doable with the [mssql](https://www.npmjs.com/package/mssql) package. I could not find in their README what parameters were mandatory and which were optional. I know if using SQL Server Management studio it is an optional item. With the [mysql](https://www.npmjs.com/package/mysql#connection-options) package it is an optional parameter.
the user can always add it later if that is their preference

**Comment by krolow** [comment]
@darkwisperer nice catch PR are welcome :smile:

**Comment by darkwisperer** [comment]
@krolow I will work on it.

**Comment by krolow** [comment]
thx @darkwisperer ;)

**Comment by darkwisperer** [comment]
According to [stackoverflow](http://stackoverflow.com/questions/4483139/how-do-i-connect-to-postgresql-without-specifying-a-database-name) PostgreSQL must have a "maintenance database" defined for connection. so this change will only affect MySQL and MS-SQL at this time. 

It was easy to turn off the error  about missing DB and be able to successfully test a connection by editing 'src/renderer/components/server-modal-form.jsx'. However in the [core](https://github.com/sqlectron/sqlectron-core) the SERVER_SCHEMA (src/validators/server.js) has the Database field as required. With this required it prevents adding the connection.  I will be submitting a PR to Core to resolve this in the next few days.

**Comment by maxcnunes** [comment]
@darkwisperer Since the database name will be required only for PG. I suggest using the [group](https://github.com/esnunes/valida#groups) configuration for the validation ([example](https://github.com/esnunes/valida/blob/master/examples/groups.js)).

**Comment by BornaP** [comment]
Regarding PostgreSQL: Why don't we just connect user to default maintenance db `postgres` if no DB is provided, it seems that's the way pgAdmin III works?

**Comment by maxcnunes** [comment]
I'm ok with this solution. It is what I usually do manually when I don't know the database name in the PG.

**Comment by BornaP** [comment]
But I think bigger problem is decoupling database param in GUI. If it won't be required, [database parameter in the route](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/entry.jsx#L21) should be either optional (?database) or there should be container component with route `/server` which would render database list (so that user can select DB) and contain current `query-browser.jsx`. Correct me if I'm wrong :smile:

**Comment by maxcnunes** [comment]
If I implement that first option: https://github.com/sqlectron/sqlectron-gui/issues/103#issuecomment-204993640. The database parameter would be removed from the route.

Maybe while while the user is not connected to a database. The query-box should be hidden e even show a message "Select a database".

**Comment by BornaP** [comment]
Yeah, that sounds great (removing database parameter from the route).

Regarding second point I agree, maybe query-box should be hidden, but on the other hand user should be enabled to create/drop databases. Maybe it should be enabled through some menu or a button if there won't be any query-box until database is selected.

**Comment by maxcnunes** [comment]
If the idea is allow the user execute queries without be connect to a specific database. I prefer let the query-box visible already. But I am not sure how the app is gonna handle executing queries without database. I guess there are a lot of stuff related to database. But I can be wrong. Is something to try out and see how goes.

**Comment by BornaP** [comment]
I compiled sqlectron-core with [this commit](https://github.com/sqlectron/sqlectron-core/pull/11/commits/263206af84dd6ddc388673726b3d56ba559bd177) and surprisingly, everything runs smoothly without having to change anything in GUI. 

Both test connection and connect works fine. When user writes query without previously selecting database, it runs as expected. 

`SELECT * FROM database_name.table_name;`

works fine, while:

`SELECT * FROM table_name;`

returns error that database is not selected.
![db_not_selected_err](https://cloud.githubusercontent.com/assets/8470710/14456975/1490ba42-00a8-11e6-8a3c-514fb46bc7e0.png)

Since this works fine, I would leave query box enabled, so that user can normally execute queries (like create/drop databases, running select with properly addressed database before table name etc.).

Only problem is one related to PostgreSQL, where if no database selected it connects to postgres. Problem is that it does not collapse postgres database list initially like it does when you manually select database. So that can confuse user at first. But I guess this can be put in another issue. Anyways, I'll try to fix it later today.

I guess it works for MSSQL as well since build is passing.

**Comment by maxcnunes** [comment]
I guess you have a problem with PG because you resolve the database name during the connection [here](https://github.com/sqlectron/sqlectron-core/pull/11/commits/263206af84dd6ddc388673726b3d56ba559bd177#diff-1e8257a7827404852fd1dfe42e66dfc1R172). And the interface by default will use the "default" database during the connection [here](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/actions/connections.js#L56).

My suggestion is:

* Expose in the sqlectron-core a variable like `defaultDatabase` [here](https://github.com/sqlectron/sqlectron-core/blob/master/src/db/clients/index.js#L11)
* Include the `defaultDatabase` as a third argument [here](https://github.com/sqlectron/sqlectron-gui/blob/master/src/renderer/actions/connections.js#L56)

**Comment by BornaP** [comment]
You were right, changed it and now it works smoothly. :clap: 

PR request is [updated](https://github.com/sqlectron/sqlectron-core/pull/11), and new one on sqlectron-gui is made. I tested it locally for MySQL and PostgreSQL and it works.

PS. Seems there is a problem with building it on AppVeyor, but it seems there is a problem in the beginning with installing modules (sqlite3), not code itself (previous build was fine and new commit shouldn't have affect it much).

**Comment by krolow** [comment]
@maxcnunes @BornaP what might happen in app if defaultDatabase does not exists any longer (example someone deleted the default db), does it handle this error properly?

**Comment by BornaP** [comment]
This is what pgAdmin III returns when you try to delete it:

> Maintenance database can't be dropped.

So I guess we don't have to worry about that.

**Comment by BornaP** [comment]
My bad, now I see if you change maintenance database you can (through console with arbitrary query). 

In that case sqlectron won't establish connection and will return:

> Connection Error
database "postgres" does not exist

User will still be able to update server connection and reconnect. Since, as far as I now, postgres is default maintenance database, if someone deletes it, it means he had to changed it to some other database so he will know the name of database he needs to connect to.

**Comment by darkwisperer** [comment]
@BornaP Thanks for jumping on this!

**Comment by BornaP** [comment]
@darkwisperer You're welcome! :)
